### ISSUE TITLE
Crash when using a language pack

### ISSUE THREAD

**Issue by ghost** [Bestsoft101/BTA-Shaders#1]
The game crashes when you load a language pack and have the shaders mod installed.

**Crash log:**

     Minecraft has crashed!
     ----------------------

Minecraft has stopped running because it encountered a problem.

If you wish to report this, please copy this entire text and post it on the forum thread at https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/3106066-better-than-adventure-for-beta-1-7-3-timely, or join the Discord server at https://betterthanadventure.net/discord and post it in #bug-reports.
Please include a description of what you did when the error occured.

     System Information
     ------------------

Generated 8/25/24, 8:51 PM
Minecraft: Better than Adventure! 7.2
OS: Windows 10 (amd64) version 10.0
Java: 17.0.10, Oracle Corporation
VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
LWJGL: 2.9.4
OpenGL: AMD Radeon (TM) R9 380 Series version 4.6.14830 Compatibility Profile Context 22.6.1 27.20.20913.2000, ATI Technologies Inc.

     Error Information
     ------------------

java.lang.RuntimeException: Error loading language file '/it_it.lang'
	at b100.shaders.LanguageHelper.loadLanguage(LanguageHelper.java:39)
	at b100.shaders.LanguageHelper.onReloadLanguages(LanguageHelper.java:21)
	at b100.shaders.asm.Listeners.onReloadLanguages(Listeners.java:352)
	at net.minecraft.core.lang.I18n.reload(I18n.java:48)
	at net.minecraft.core.lang.I18n.reload(I18n.java:29)
	at net.minecraft.core.lang.I18n.<init>(I18n.java:24)
	at net.minecraft.core.lang.I18n.initialize(I18n.java:16)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:359)
	at net.minecraft.client.Minecraft.run(Minecraft.java:786)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URL.openStream()" because "url" is null
	at b100.shaders.LanguageHelper.loadLanguage(LanguageHelper.java:32)
	... 9 more

**Comment by Bestsoft101** [comment]
Fixed
https://github.com/Bestsoft101/BTA-Shaders/commit/223228deebc3ebc7533aeab8888ae6ce21d9b71f
